import 'element-plus/es/components/dropdown/style/css'
import 'element-plus/es/components/button/style/css'
import 'element-plus/es/components/dropdown-menu/style/css'
import 'element-plus/es/components/tree/style/css'
import './vars'
import './column-setting.css'
