import 'element-plus/es/components/button/style/css'
import 'element-plus/es/components/dialog/style/css'
import './form'
import './search'
import './table'
import './descriptions'
import './crud.css'
