import 'element-plus/es/components/select/style/css'
import 'element-plus/es/components/option-group/style/css'
import 'element-plus/es/components/option/style/css'
import './vars'
import './select.css'
