import 'element-plus/es/components/select/style/css'
import 'element-plus/es/components/option/style/css'
import 'element-plus/es/components/tree/style/css'
import './vars'
import './tree-select.css'
