name: Deploy docs

on:
  workflow_dispatch:
  release:
    types: [ created ]
  push:
    tags:
      - 'v**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build:docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.page }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
