name: test

on:
  pull_request:
    branches: [ main, releases ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Install and Test
        run: |
          pnpm install
          pnpm run test
